// Generated by CoffeeScript 1.7.1
var addMarkers, createMap, map, view;

createMap = function() {
  return new google.maps.Map(document.getElementById('map'), {
    zoom: 6,
    center: new google.maps.LatLng(36.3, -118),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
};

view = function() {
  return [
    'div', ['p', '根据邮政编码显示签名数：'], [
      '#map', {
        style: {
          width: '100%',
          height: 700
        }
      }
    ]
  ];
};

T(view()).render({
  inside: '#container'
});

addMarkers = function(map, data) {
  var icon, marker, position, zip, zipData, _results;
  _results = [];
  for (zip in data) {
    zipData = data[zip];
    if (zipData.signed <= 0) {
      continue;
    }
    position = new google.maps.LatLng(zipData.latitude, zipData.longitude);
    icon = "/augment/images/markers/marker" + (zipData.signed > 99 ? 99 : zipData.signed) + ".png";
    _results.push(marker = new google.maps.Marker({
      map: map,
      position: position,
      animation: google.maps.Animation.DROP,
      title: zip,
      icon: icon,
      zIndex: zipData.signed
    }));
  }
  return _results;
};

map = createMap();

if (location.host.match(/capeus.org/)) {
  jQuery.getJSON("http://gcao.cloudant.com/cape/sca5signatures?callback=?", function(resp) {
    return addMarkers(map, resp.data);
  });
} else {
  addMarkers(map, data);
}
